### PR TITLE
Implement crypto signing and verification as researched - close #123, close #128

### LINKED ISSUE #123: Find out how to do signing ([with Mist] + ether accounts)
# Task
## Detailed Description

- ?
## Associated story

Story: #122  Validate and acknowledge received moves

### LINKED ISSUE #128: Find out how to validate signatures in BC
# Task
## Detailed Description

- ?
## Associated story

Story: #127 Claim checkmate, stalemate and surrender and submit to BC/claim ether

### PR DESCRIPTION
**Pull request by kyroy**
## Description

Implement crypto signing and verification as researched
## Related Issue

#123 Find out how to do signing ([with Mist] + ether accounts)
#128 Find out how to validate signatures in BC
## Motivation and Context

Ease the usage of crypto functions
## Notes

Merge #132 first!
## Checklist reviewer:
- [x] The code has been peer-reviewed by @graup

### CODE REVIEW

**Comment by graup** [comment]
Would it be possible to re-commit this without all the changes to the contract that somehow ended up in here? That messes up the git history. Basically rebase in a way that doesn't make my Refactor commit part of this branch.

**Comment by Kyroy** [comment]
I think this is overhead we do not need. Just check cryptoFactory.js and contract/Auth.sol

**Comment by kyroy** [comment]
Done

**Comment by graup** [comment]
Perfect, thanks!

**Pull request merged**
